apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: monitoring
  name: prometheus-deployment
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prometheus-deployment
  targetCPUUtilizationPercentage: 90