version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      DATABASE_URL: postgresql://user:password@db/mydatabase
      SECRET_KEY_JWT: secreto
      CORS_URL: http://localhost:8080
    depends_on:
      - db

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 

volumes:
  postgres_data: