apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: platform
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 3000  # Puerto estándar HTTP en lugar de 8080
      targetPort: 3000 
  type: NodePort  #  O LoadBalancer si estás en la nube
