apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: platform
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: rvvaldes/platform:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: postgresql://user:password@postgres.platform.svc.cluster.local:5432/mydatabase  # FQDN para el servicio de PostgreSQL
            - name: SECRET_KEY_JWT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret
            - name: CORS_URL
              value: http://front:8080  # Referencia al servicio 'front' por nombre
          resources:
            requests:
              cpu: 100m     # Valores de recursos más conservadores para comenzar
              memory: 128Mi 
            limits:
              cpu: 250m
              memory: 500Mi
