apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: platform
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      email VARCHAR(100) UNIQUE NOT NULL
    );

    INSERT INTO users (name, email) VALUES ('admin', 'admin@dominio.com');

