name: App Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'code/app/**'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Use Buildx for faster/multi-platform builds

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io  # Specify the registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: code/app 
          push: true
          tags: rvvaldes/platform:latest
          # Consider adding cache for faster builds:
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-kubernetes-cluster:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG }}

      - name: Deploy to cluster
        run: kubectl rollout restart deployment app -n platform --insecure-skip-tls-verify  # Use rollout restart

      - name: Verify deployment
        run: kubectl rollout status deployment app -n platform --insecure-skip-tls-verify # Wait for successful rollout
